### ISSUE TITLE
DOC: Specify that instances of physical_constants are frozen

### ISSUE THREAD

**Issue by valerio-marra** [LSSTDESC/CCL#1007]
Hi, if I do
`ccl.physical_constants.GNEWT=Gdef`
i get
`AttributeError: Instances of physical_constants are frozen.`

However, this works with an earlier version of CCL (as also mentioned [here](https://ccl.readthedocs.io/en/latest/source/notation_and_other_cosmological_conventions.html#specifying-physical-constants)).

**Comment by nikfilippas** [comment]
This is expected behavior, the values of the physical constants can't be changed since v2.5.1.
GNEWT, in particular, is connected to the value of RHO_CRITICAL, and the value of the SOLAR_MASS (since we use G to calculate it), so I wouldn't suggest changing it, or most of the background calculations will be wrong.

However, if you really know what you are doing, you can hack in your preferred value via
`ccl.physical_constants._instance.GNEWT = my_value`, which will throw a warning, or `object.__setattr__(ccl.physical_constants._instance, "GNEWT", my_value)` which won't.

Thanks for pointing out the omission in the docs, we will be doing an overhaul of the docs before the new release.

**Comment by valerio-marra** [comment]
thanks! (i'm changing these values to exactly match the ones i used when running simulations)
