### ISSUE TITLE
Setting a Constant Magnificataion Bias

### ISSUE THREAD

**Issue by paulrogozenski** [LSSTDESC/CCL#1009]
When calculating a constant zero magnification bias across all redshifts and setting has_mag = True, ccl_get_lensing_mag_kernel in ccl_tracers.i returns a non-zero value. In my experience when setting a constant magnification bias, it acts as a prefactor to the kernel. Is there a different notation used in CCL, or is there an error in the integration of the code?

As an example,

`    t_m = ccl.NumberCountsTracer(ccl_cosmo, has_rsd=False, dndz=(lens_z, lens_nz), bias=None, mag_bias=(lens_z, np.ones_like(lens_z)*0.0))
c_l = ccl.angular_cl(ccl_cosmo, t_m, t_m, ells_ggl)
`
Here, c_l will be non-zero. Thank you!

**Comment by c-d-leonard** [comment]
I think this will just be a difference in definition - the way it is defined in CCL it is additive to the usual number counts correlation function, see section 2.4 of https://arxiv.org/pdf/1812.05995.pdf

**Comment by c-d-leonard** [comment]
Looking at this a bit more: 
- I think that `ccl_get_lensing_mag_kernel` in ccl_tracers.i is returning non-zero because it is intended to return either the shear kernel (if magnification bias is 0) or the magnification kernel (if magnification bias is non-zero). You can see this in the function `ccl_get_lensing_mag_kernel` in src/ccl_tracers.c. So that part I think is behaving as expected. 
- However, I agree that I would not expect c_ell to be non-zero in the example you give. Can you post a plot of the c_ell you do get in that case?
