### ISSUE TITLE
Extending integration range for calculation of P(k) from Halo Model

### ISSUE THREAD

**Issue by andrearubiola** [LSSTDESC/CCL#1010]
Good evening, 

I found [this discussion](https://github.com/LSSTDESC/CCL/issues/915#issue-1097992943) addressing a problem similar to mine. 

Is there a way to extend the lower and upper limits of the mass integrals below 1e6 M_sun and above 1e17 M_sun? 
I tried to modify the GSL parameters HM_MMIN and HM_MMAX before instantiating the HMCalculator and hence the power spectrum calculator, but to no avail.

Thanks
Andrea

**Comment by nikfilippas** [comment]
You can specify the limits as arguments of your halo model calculator: https://ccl.readthedocs.io/en/latest/api/pyccl.halos.halo_model.html.

Closing this but feel free to reopen if this remains an issue.

**Comment by andrearubiola** [comment]
No, this is *not working*. If I change those argument to, say, 1e5  M_sun, the program returns an error. This is also why I was trying to modify the HM_MMIN and HM_MMAX  parameters.

**Comment by nikfilippas** [comment]
Ah, I see now, you want to query the mass function and halo bias above and below the preset [1e6, 1e17] limits.
To do this CCL needs uses the sigmaM spline which is computed once, and is stored in the `cosmo` object. The error you are getting is because you are querying values outside of the sigmaM spline boundaries.
These are controlled via `ccl.spline_params.LOGM_SPLINE_MIN` and `ccl.spline_params.LOGM_SPLINE_MAX`.

Note, however, that this is generally dangerous. The implemented mass bias and halo bias functions are not calibrated for such extreme ranges. In particular, the HM calculation includes the small-mass contribution in the calculation of the power spectrum, so unless your usecase is very specific, there is no need to go beyond 1e6.

**Comment by andrearubiola** [comment]
Thanks, I was just trying to make sure pyccl allows this degree of freedom.
I'll subsequently check sensibility and stability of the output, thank you.

Il mar 13 dic 2022, 18:36 Nick Koukoufilippas ***@***.***> ha
scritto:
