### ISSUE TITLE
Normalisation of the kernels/window function in the calculation of the C_l's

### ISSUE THREAD

**Issue by andrearubiola** [LSSTDESC/CCL#1022]
Good morning,

It is not really clear - even digging into the code down to the C++ files, whether the kernel are normalised by the functions calculating the power spectra or we have to do it by hand before feeding them into the C_l calculator. In other words, does the code do the expression below on its own? If so, how are the integration extremes chosen?

![immagine](https://user-images.githubusercontent.com/59877325/220850854-6aad7a28-9573-4711-9b52-48e72e3f5cb5.png)

Thanks
Andrea

**Comment by damonge** [comment]
Hi @andrearubiola . If you create a tracer from scratch (i.e. passing it the kernel directly), pyccl will interpret the kernel directly, with no modifications to it. This makes sense, since most kernels are actually not normalised.

However, if you create a `NumberCounts` or `WeakLensing` tracer, the redshift distribution you pass it, will be normalised to unit area (as it should be!). This is specified in the documentation (see e.g. https://ccl.readthedocs.io/en/latest/api/pyccl.tracers.html#pyccl.tracers.NumberCountsTracer).

**Comment by andrearubiola** [comment]
Perfect! Thank you very much. A suggestion for further developments of the code might be making a normalise/non normalise option explicitly available in the code. 
Best
Andrea
