### ISSUE TITLE
Implement approximated halo model trispectrum

### ISSUE THREAD

**Issue by carlosggarcia** [LSSTDESC/CCL#1140]
I think it should be good to have this approximation (Eq. A4 in https://arxiv.org/pdf/1601.05779.pdf) for the cNG in TJPCov

![image](https://github.com/LSSTDESC/CCL/assets/17812754/0244fa8f-d4c7-459b-b010-658979bde68e)

**Comment by damonge** [comment]
@carlosggarcia isn't it sufficiently easy for users to just create the matter trispectrum themselves using NFW profiles and just multiply the result by whatever biases they want? This is a bit trickier for the SSC due to the counterterm, and that's why we implemented that function, but for the cNG trispectra is a lot more trivial -- and I worry about having to maintain one more function.

**Comment by carlosggarcia** [comment]
I think you are right. Not sure why I thought one cannot factor out the biases in the 1h term.

**Comment by damonge** [comment]
One cannot factor out the biases in that case, that's fine, but you can in all other three. This is different from the SSC case, where the biases cannot be factored out anywhere. I'll close this for now, but feel free to reopen.
