### ISSUE TITLE
Installation with conda installs new compilers and kernel headers

### ISSUE THREAD

**Issue by caioolivv** [LSSTDESC/CCL#1183]
Installing pyccl with conda from conda-forge forces the installation of new compilers and kernel headers, which breaks other libraries in the environment (in specific, NumCosmo). Is this expected behavior?

(At the moment, I can still install with pip so that's not a big problem)

![image](https://github.com/LSSTDESC/CCL/assets/38115797/dce5fdc5-88c2-4d28-9318-d20ad0466ab3)

**Comment by erykoff** [comment]
This appears to be because the `camb` conda-forge feedstock defines the fortran compiler as a run requirement which is ... odd.

**Comment by caioolivv** [comment]
Any way to go around this? I'm trying to install firecrown which requires pyccl through conda, so I'm not able to install it on the same environment as NumCosmo.

**Comment by erykoff** [comment]
Pinging @beckermr on this.

**Comment by beckermr** [comment]
Is numcosmo packaged in conda-forge?

**Comment by beckermr** [comment]
Got it. Thanks for the quick response.

conda + camb is doing the right thing here. 

The issue is that you have a requirement on the compilers that you didn't tell conda about. You can tell conda about it by putting the requirements on the compilers into the conda-meta/pinned file in your environment's prefix. You can make that file if it does not exist.

Then conda will respect those pins when it does operations on the env.

**Comment by damonge** [comment]
I'm gonna close this one, but @caioolivv , let me know if Matt's solution doesn't work.
