### ISSUE TITLE
Discuss python-only CCL routines

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#227]
Are there CCL routines that we would like to make available in python only? Would this help users develop new CCL features? When do we need C implementation? This is a discussion topic. @dkirkby

**Comment by tmcclintock** [comment]
lol @ the labels

**Comment by jablazek** [comment]
If this is an option, it would be a fast way to start playing with FAST-PT, which is pure python.

**Comment by tmcclintock** [comment]
For reference: [embedding python in another language](https://docs.python.org/2/extending/embedding.html).

**Comment by philbull** [comment]
We already have some code that can call Python from the C library. It is generally quite slow if you have to make a lot of function calls, as they come with a lot of overhead. A single function call shouldn't be too slow though. There will also be some added overhead in the build system, as we'd need to link against Python.

**Comment by dkirkby** [comment]
Some relevant points for the discussion:
 - It is easier (and more fun) to add a new feature in python (rather than C).
 - Numerics in python can be slower than C, but the performance is often close (using numpy, etc) and most of the CCL code will not be a bottleneck in any language.
 - The pool of experienced DESC python developers is probably larger than the pool of experienced C developers.

The key issue is do we have clients that require the full C API?  In particular, do the WG likelihood writers expect or require C access to all features?  Perhaps we could poll them, with the proposal that all likelihoods be written in python?

**Comment by villarrealas** [comment]
#554 is directly relevant to this. Since the latter has discussion in the last year, I am closing this thread and cross-referencing.
