### ISSUE TITLE
Request for CCL module on NERSC

### ISSUE THREAD

**Issue by villarrealas** [LSSTDESC/CCL#233]
Some NERSC users have had difficulties installing CCL and have suggested that there should be a request for it to be made a module on that system. It should be a matter of just getting sufficient people with NERSC accounts to request that it be turned into an environment module.

**Comment by heather999** [comment]
There is now a central installation of CCL 0.2 at NERSC on Cori using NERSC's  gsl, fftw and swig in:
```/global/common/cori/contrib/lsst/ccl/0.2```
There were some tweaks required to the vanilla environment.  The Python wrappers are also set up in a Python2 conda environment named CCL.  There are two set up files available for those who might want to try this out.  To use the CCL C installation:
```source /global/common/cori/contrib/lsst/ccl/setupCCL.sh```
and the python wrappers are available here:
```source /global/common/cori/contrib/lsst/ccl/setupPyCCL.sh```

**Comment by heather999** [comment]
The above NERSC installation could be used as the base for a module file:
http://www.nersc.gov/users/software/nersc-user-environment/modules/#toc-anchor-3
One of the NERSC folks suggested that setting up a Docker/Shifter image might be a better way to go but I think that really may depend on your use case - if this is for interactive use or batch jobs.
I can attempt to make a module file and see what happens :)

**Comment by elisachisari** [comment]
@heather999 Can this issue be closed? Do we have a working CCL module in NERSC?

**Comment by WeikangLin** [comment]
@heather999 I recently got an account at NERSE and try to use the central installed CCL at NERSCE or install CCL on my own. After doing 
   `source /global/common/cori/contrib/lsst/ccl/setupPyCCL.sh`
I can compile and run, e.g., tests/ccl_sample_run.c with the central installed CCL.

I however fail to install CCL to an assigned path. 
I first do
   `source /global/common/cori/contrib/lsst/ccl/setupCCL.sh`,
then
   `./configure --prefix=/global/homes/w/weikang/CCL_LIB`,
and it looks fine.
But when I do `make`, an error shows up as
   /usr/bin/ld: attempted static link of dynamic object `/global/homes/w/weikang/DESC/CCL/.libs/libccl.so'.
Did I miss something? Thank you in advance.

**Comment by fjaviersanchez** [comment]
So this is the reason why it complains: http://www.nersc.gov/users/computational-systems/edison/running-jobs/shared-and-dynamic-libraries/

But you can solve it just doing `export CFLAGS="-dynamic"` before `./configure --prefix=/YOUR/PATH/TO/INSTALL` and it should work :)

**Comment by WeikangLin** [comment]
@fjaviersanchez Thank you very much for your response. After doing `export CFLAGS="-dynamic"`, I still have problem:
```
/usr/bin/ld: /usr/lib64/libmvec_nonshared.a(svml_finite_alias.oS): relocation R_X86_64_PC32 against undefined symbol `_ZGVbN2v_log@@GLIBC_2.22' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```
Any suggestions?

**Comment by fjaviersanchez** [comment]
that looks like you are using the gnu programming environment and it is complaining. You can try to do `make clean` first and `module swap PrgEnv-gnu PrgEnv-intel` and try again to do the `export CFLAGS...` and `./configure`

**Comment by WeikangLin** [comment]
With @fjaviersanchez 's help, I get CCL installed on NERSC at an assigned location using NERSC's gsl, fftw and swig. The following could be done before trying to install CCL:
1. `module load gsl/2.1`
2. `module load fftw`
3. `module load swig`
4. `export LDFLAGS+="-L$GSL_DIR/lib -L$FFTW_DIR"`
5. `export CPPFLAGS+="-I$GSL_DIR/include -I$FFTW_DIR/../include"`

**Comment by rainwoodman** [comment]
The current version of glibc on nersc doesnt work with the 6.x gcc due to a
bug in glibc.

 swap GCC  to 5.x shall fix this too if you don't want use Intel compiler.


On Sep 13, 2017 10:57 AM, "fjaviersanchez" <notifications@github.com> wrote:

that looks like you are using the gnu programming environment and it is
complaining. You can try to do make clean first and module swap PrgEnv-gnu
PrgEnv-intel and try again to do the export CFLAGS... and ./configure

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LSSTDESC/CCL/issues/233#issuecomment-329247698>, or mute
the thread

**Comment by heather999** [comment]
@elisachisari I'm sorry to say while there is an installation of CCL at NERSC, there is no module file.  It might be nice to have that set up, but it is also not necessarily required.  I will contact @damonge and try to push on.

**Comment by heather999** [comment]
@WeikangLin & @fjaviersanchez  I am still catching up.  So the central installation of 0.2 works? I just want to make sure that it is ok. The setup indicated above is very close to what we have in /global/common/cori/contrib/lsst/ccl/setupCCL.sh, however I used gnu, rather than intel. When using the gsl module, it is my understanding that we cannot use gcc directly, but rather call cc instead:

> On Cori or Edison if you want to use the gcc compiler and GSL you must swap the modulefiles for the programming environments.  DO NOT invoke gcc directly. 

http://www.nersc.gov/users/software/programming-libraries/math-libraries/gsl/
So I export CC=cc in the setupCCL.sh file and things seemed to be ok.

However you were having trouble building your own CCL at NERSC (which version?) but it sounds like that is now working.  We could provide a similar script that sets up the NERSC environment to allow others to do their builds as well.. maybe something like cclInstallEnv.sh. That might be useful to developers if they're going to building at NERSC.

**Comment by WeikangLin** [comment]
Thanks @heather999. The central installation of 0.2 works for me. Upon logging in NERSC (cori), I do `source source /global/common/cori/contrib/lsst/ccl/setupPyCCL.sh`. I can then compile tests/ccl_sample_run.c by `gcc -Wall -Wpedantic -g -I$CCL_NERSC_DIR/$CCL_NERSC_VER/include $CPPFLAGS -std=gnu99 -fPIC tests/ccl_sample_run.c -o tests/ccl_sample_run -L$CCL_NERSC_DIR/$CCL_NERSC_VER/lib $LDFLAGS -lgsl -lgslcblas -lm -lccl` and run it. I however used gcc instead of cc to compile the code. But if I do `source source /global/common/cori/contrib/lsst/ccl/setupCCL.sh` and try to compile, I have a problem when trying to run ./tests/ccl_sample_run: `tests/ccl_sample_run: error while loading shared libraries: libccl.so.0: cannot open shared object file: No such file or directory`. Probably `export LD_LIBRARY_PATH=/opt/cray/pe/pmi/5.0.10-1.0000.11050.0.0.ari/lib64:$CCL_NERSC_DIR/$CCL_NERSC_VER/lib:$LD_LIBRARY_PATH` is missing?

If I want to install CCL in a specific path, I had problems. Originally, Upon logging in NERSC, I did `source source /global/common/cori/contrib/lsst/ccl/setupCCL.sh`, but an error showed up when I came to `make` as `/usr/bin/ld: attempted static link of dynamic object `/global/homes/w/weikang/DESC/CCL/.libs/libccl.so'`. I am using the version in the current master branch in the CCL repository.

With @fjaviersanchez 's help, I found that the above five steps works for me. It doesn't have `module swap PrgEnv-intel PrgEnv-gnu`, so I guess I am using intel. It doesn't have `export CC=cc`, and probably because I am using intel as well? And I also need to add the fftw/include path to CCPFLAGS. 

A script for installing CCL sounds good. I will appreciate it.

**Comment by villarrealas** [comment]
CCL is accessible on NERSC now and this issue is outdated, so this is being closed.
