### ISSUE TITLE
Seg fault when using eisenstein_hu

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/CCL#246]
This piece of code seg faults for me:
```
import pyccl as ccl
import numpy as np
p = ccl.Parameters(Omega_c=0.25, Omega_b=0.05, h=0.7, A_s=2.1e-9, n_s=0.96)
cosmo = ccl.Cosmology(p, transfer_function='eisenstein_hu')
k = np.logspace(-3, 2, base=10, num=100)
P = ccl.linear_matter_power(cosmo, k, a=1.0)
```
It runs fine if I don't specify the transfer function.

This is on a machine I just installed CCL on, but I don't believe this is the issue.

**Comment by fjaviersanchez** [comment]
@tmcclintock Is this only with eisenstein and hu or does it happen for any `ccl.linear_matter_power`?

**Comment by tmcclintock** [comment]
@fjaviersanchez the only transfer function types that it doesn't fail on are 'boltzmann', 'boltzmann_class' (which is the default), and 'class' (which uses to the same thing as 'boltzmann_class').

**Comment by fjaviersanchez** [comment]
@tmcclintock I was thinking that it might be some problem with the gsl version that it's calling at runtime or some difference between the compiler that you used to generate gsl and to install the libraries but, if it's running with class (which I think that also call gsl) I don't know what it can be... Maybe @damonge has some ideas since I think that he implemented that part. Sorry about that.

**Comment by elisachisari** [comment]
@tmcclintock @philbull 

I'm seeing this too in master. If you call the cosmology with sigma8 rather than A_s, you don't get the segfault. This is indeed a bug because according to the note you should be able to pass either sigma8 or A_s in python and it should work. 

![screen shot 2017-09-01 at 18 40 42](https://user-images.githubusercontent.com/9137015/29981336-3afdff3c-8f45-11e7-9aa4-8967cc55eb72.png)

So we should check the python implementation to make sure that it accepts A_s as well as sigma8. 

Another thing to note is that we no longer construct a parameters struct, but pass them directly to ccl.Cosmology. (Although that doesn't seem to be causing problems.) See the [jupyter notebook](https://github.com/LSSTDESC/CCL/blob/master/tests/Power%20spectrum%20example.ipynb).

**Comment by elisachisari** [comment]
This could be added as a unit test in the python suite and we could also add a benchmark check entirely in python.

**Comment by tmcclintock** [comment]
Yes, I saw @damonge 's mention of this on the slack channel. Thanks for tracking it down concretely though, @elisachisari.

The options are to make it super-apparent to the user that they have to use sigma8 instead of A_s, or to make it so that if A_s is passed in then sigma8 is calculated for them before the power spectrum is called, but I don't think this is possible since, ya know, we can't get to the power spectrum. Thoughts?

**Comment by elisachisari** [comment]
It might be possible to implement this option that you suggest. We had the inverse implemented in C, where if you passed sigma8, you find A_s before you call CLASS. I think @elikrause implemented this. 
Is this problem also there in C when you call the PS with A_s and Eisenstein & Hu transfer function?

**Comment by tmcclintock** [comment]
After doing a completely fresh install (with root) on a Mac laptop, I have reproduced this bug exactly. Since I am already going to be working on getting valgrind working for CCL, I'll assign myself this bug as well.

**Comment by elisachisari** [comment]
@tmcclintock would you be up for adding an error message in CCL for this case?

**Comment by tmcclintock** [comment]
Might be a bit early. I still am not convinced it's not some kind of screw up in the installation on my part. Otherwise yes I will.

**Comment by tmcclintock** [comment]
I did a fresh install again and the issue is gone.

Magic.

I'm going to close this.
