### ISSUE TITLE
Default values for baryonic parameters

### ISSUE THREAD

**Issue by c-d-leonard** [LSSTDESC/CCL#277]
We need to make sure of what happens if we pass a parameter structure without baryonic parameters but with the baryons flag set to Yes.

**Comment by elisachisari** [comment]
I tried this first in C using `ccl_sample_baryons`. If the baryons flag is set to Yes but you don't pass any values for the baryonic parameters, default values are assumed. This choice is implemented within `ccl_core.c`. No-baryons cosmology parameter creation routines basically call the general `ccl_params_create` routine with baryonic parameters set to -1. This triggers the use of fiducial values from the BCM model.

Likewise for pyccl. If you go to the [Power spectrum notebook](https://github.com/LSSTDESC/CCL/blob/master/tests/Power%20spectrum%20example.ipynb), you will find an example at the bottom which shows that if you call the nonlinear matter power spectrum from pyccl with the baryons set to Yes, but you don't pass any baryonic parameters, you get the fiducial BCM parameters by default. This is because baryonic parameters are initialised to fiducial in `core.py` when the Parameters class is defined.

I think this clarified this issue, and there are no action items, so I'll close it.
