### ISSUE TITLE
Incorporate NumCosmo as a module?

### ISSUE THREAD

**Issue by pennalima** [LSSTDESC/CCL#363]
The Numerical Cosmology library (NumCosmo - https://github.com/NumCosmo/NumCosmo - https://numcosmo.github.io/)  is a free software C library whose main purposes are to test cosmological models using observational data and to provide a set of tools to perform cosmological calculations. Besides the functions related to cosmology, NumCosmo also provide mathematical and statistical tools.

In particular, I am implementing codes to estimate cluster masses via weak lensing. This work is part of  the CLMassMod project of the CL WG. 

NumCosmo can be installed via conda - 
conda-forge package: https://anaconda.org/conda-forge/numcosmo

**Comment by philbull** [comment]
Hi @pennalima, thanks for filing this issue. CCL seems to have a lot of overlap with NumCosmo, so I'm not sure what we'd gain by integrating it into CCL. Users who want to use NumCosmo can just import it separately, can't they?

If we include both the CCL and NumCosmo routines in the same package, it might cause confusion, as people will have to choose whether to use the default CCL implementation of a function (e.g. the matter power spectrum), or the NumCosmo routine. The aim of CCL is to provide a single uniform interface to all of the cosmological functions that are needed within DESC. These functions are also validated for accuracy (i.e. to a target precision of 10^-4). I'm not sure if this is the case for NumCosmo, as it seems like a more general-purpose package.

**Comment by philbull** [comment]
Also, we are hoping that most users within DESC will use CCL by default, instead of external cosmology packages. This is to ensure consistency between different probes. If the CL working group is using different routines to everyone else, there's a risk of introducing inconsistencies. It also means that the external libraries will need to be tested/validated separately, which creates more work.

Are there some features that you need in CCL that aren't there? If so, we're happy to discuss implementing them. If not, we strongly recommend using CCL for DESC-related work instead!

**Comment by salmanhabib** [comment]
Or at least use CCL as a standard reference, @philbull ? It is always good to compute things different ways to make sure the answers agree. If CCL does not agree with method X, it will be important to figure out why, rather than just use the CCL answer. I think this is a more or less obvious point, but I always like to see people not relying on inherited wisdom, but doing a lot of checking and testing. getting off the soap box now ;-)

**Comment by pennalima** [comment]
Hi @salmanhabib,

I agree it is good to have different independent codes to cross-check the computations/analyses. 

"These functions are also validated for accuracy (i.e. to a target precision of 10^-4). I'm not sure if this is the case for NumCosmo, as it seems like a more general-purpose package."
@philbull 
Yes, we also validate our codes. 
target precision of 10^-4 for the "final" cosmological constraints? Or this precision is required for each function? (some functions we require precision > 10^-4) 
I the CCL team are interested, I could cross-check CCL and NumCosmo. (or have you been comparing CCL codes with others?) 
What do you think?

**Comment by tmcclintock** [comment]
@pennalima the cluster_toolkit doesn't implement anything itself that CCL already has. For instance calculating power spectra, the toolkit requires something like CCL. It does have old implementations of things like the halo bias and halo mass function that produce identical outputs to CCL. My feeling is that if the toolkit were to be a subclass of CCL then those functions would get removed from the toolkit, or at least everything would be rearranged.

Personally, from a design perspective, I think it would make sense to have a "halo" module that had everything related to the halo model in it (bias, mass function, density profiles, lensing profiles, etc.). Additionally, given that the dependencies of CCL are already strict and cause near endless headaches for those trying to install, my preference would be to just reimplement the functions in the cluster_toolkit, NumCosmo, and possibly some features of CLMM in CCL rather than subclassing or forcing a dependence.

**Comment by salmanhabib** [comment]
I think a rigorous program of independent code cross-verification is very important. My experience with the cosmological simulation community has made me very skeptical of internal claims of code accuracy. The 10**-4 requirement is actually quite stringent. 

Also, a moment's thought should be enough to convince anyone that many inputs into the CCL (e.g., mass functions) have no chance of meeting this accuracy level as raw inputs. So what are we going to do about that? We need solid statements about the accuracy requirement for each significant input variable and the assumptions under which that accuracy holds. A (living) technical document suggestion for TJP --

**Comment by pennalima** [comment]
Hi @salmanhabib,

I agree it is good to have different independent codes to cross-check the computations/analyses. 

"These functions are also validated for accuracy (i.e. to a target precision of 10^-4). I'm not sure if this is the case for NumCosmo, as it seems like a more general-purpose package."
@philbull 
Yes, we also validate our codes. 
target precision of 10^-4 for the "final" cosmological constraints? Or this precision is required for each function? (some functions we require precision > 10^-4) 
I the CCL team are interested, I could cross-check CCL and NumCosmo. (or have you been comparing CCL codes with others?) 
What do you think?

**Comment by pennalima** [comment]
Hi @philbull, @salmanhabib  and @tmcclintock ,

Thanks for the input!
I've discussed this issue with @vitenti (Sandro Vitenti - the main developper of NumCosmo) and he suggested to encapsulate CCL on NumCosmo. 
Let's discuss this in more details in the telecon.

**Comment by beckermr** [comment]
I think from the discussion today with @pennalima we can close this issue. Feel free to reopen if I missed something.
