### ISSUE TITLE
CLASS thermodynamics issues when doing pip install

### ISSUE THREAD

**Issue by alexander-mead** [LSSTDESC/CCL#411]
With the new `pip install pyccl` system I am running into problems when running the `Power Spectrum example.ipynb` notebooks. I am running the latest CCL version and have up-to-date OSx.

If I do `pip install pyccl` then run the notebook I get the following error:

```
RuntimeError: Error CCL_ERROR_CLASS: ccl_power.c: ccl_cosmology_compute_power_class(): Error running CLASS thermodynamics:thermodynamics_init(L:304) :error in thermodynamics_helium_from_bbn(ppr,pba,pth);
=>thermodynamics_helium_from_bbn(L:1143) :could not open fA with name /private/var/folders/vz/3cw9xc9940d1f75qgkmvd65c0000gn/T/pip-install-LFr7Cs/pyccl/build/CLASS/src/CLASS/bbn/sBBN_2017.dat and mode "r"
```

whereas everything works fine when I install CCL via `python setup.py install`.

**Comment by EiffL** [comment]
Just to document my findings, the problem comes from the fact that CLASS loads a bunch of files at runtime, from a hardcoded path... When we install with pip, CCL and CLASS are compiled in a temp dictionary, and then moved to an install location, while the build directory gets deleted. At which point, CLASS stops working. The reason why all the tests pass on travis is that the CLASS build directory survives. 

@tilmantroester , @elisachisari found a bug in which the 3x2pt example notebook doesnt work on a pip install, where a bunch of messages like this appear:
```
WARNING: ccl_cls.c: ccl_angular_cl_native(): GSL error: generic failure
WARNING: ccl_cls.c: ccl_angular_cl_native(): GSL error: generic failure
WARNING: ccl_cls.c: ccl_angular_cl_native(): GSL error: generic failure
WARNING: ccl_cls.c: ccl_angular_cl_native(): GSL error: generic failure
...
```
At first it looks like this is completely uncorrelated, but I suspect that an error related to CLASS gets tiggered abd then caught by `ccl_raise_gsl_warning` here: 
https://github.com/LSSTDESC/CCL/blob/a7d6c59158789df03758502b8bd5476bc59a6797/src/ccl_cls.c#L1154

But I don't think the error gets properly propagated, so that we don't see any message about CLASS.

I'm looking into the issue, but CLASS is the culprit here, and more specifally, these lines:
https://github.com/lesgourg/class_public/blob/db1589b94eb60dd0f7a908592bb8541bb576cd12/source/input.c#L3229

https://github.com/lesgourg/class_public/blob/db1589b94eb60dd0f7a908592bb8541bb576cd12/source/input.c#L3191

Essentially, we just need a way to either specify at runtime the path to these files, or hardcode the path to the CCL install directory...
