### ISSUE TITLE
Add CMB predictions

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#428]
Add CMB observables beyond lensing to CCL, as combined probed analyses form LSST will include them. These predictions can be directly output from CLASS, we just need to link them in the right way.

Suggested by @dodelson.

**Comment by dodelson** [comment]
Wow, what fast service! I'm hooked

Sent from my iPhone

On Jul 24, 2018, at 4:34 PM, elisachisari <notifications@github.com<mailto:notifications@github.com>> wrote:


Add CMB observables beyond lensing to CCL, as combined probed analyses form LSST will include them. These predictions can be directly output from CLASS, we just need to link them in the right way.

Suggested by @dodelson<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dodelson&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=1sg686L92HgxpQF5wXl0sz3VthEo02F_vNwrcDNjAdw&m=mz9PISEH4bywwH-449ByuSORjo43BfgDoCwABUhq93U&s=c0DxnN2Lo-ORngMD0Ef0nxpPPnC5_GgcsaW6TkVcDsE&e=>.

**Comment by villarrealas** [comment]
Should we also seek to offer something more general than CLASS, given we are moving away from that as a core dependency? I do not do CMB work, so I am uncertain how feasible this is.

**Comment by damonge** [comment]
I think for CMB primary that's perfectly fine. The only thing we would probably want to add explicitly in CCL are auto- and cross-correlations with the secondary anisotropies (ISW, tSZ, kSZ, maybe CIB? CMB lensing is already there)

**Comment by dodelson** [comment]
It might be useful at this early stage to consider timing. In des chains, we are having problems running with cmb as each sample can take up to 20 sec

Sent from my iPhone

On Jul 24, 2018, at 4:52 PM, David Alonso <notifications@github.com<mailto:notifications@github.com>> wrote:


I think for CMB primary that's perfectly fine. The only thing we would probably want to add explicitly in CCL are auto- and cross-correlations with the secondary anisotropies (ISW, tSZ, kSZ, maybe CIB? CMB lensing is already there)

**Comment by damonge** [comment]
Mmh, is this because you're asking for both CMB and P(k) at low z at the same time and it takes too long to solve the perturbation equations? Otherwise CMB people should encounter the same issues, I guess.

**Comment by dodelson** [comment]
Yes i think you're right, and part of solving that is choosing settings in, e.g. Camb optimally

Sent from my iPhone

On Jul 24, 2018, at 4:57 PM, David Alonso <notifications@github.com<mailto:notifications@github.com>> wrote:


Mmh, is this because you're asking for both CMB and P(k) at low z at the same time and it takes too long to solve the perturbation equations? Otherwise CMB people should encounter the same issues, I guess.

**Comment by beckermr** [comment]
Reupping this issue. We discussed this in the context of firecrown a bit today. The basic options are to

1. Enable CCL to produce the proper CMB predictions.
2. Only call CLASS from python outside of CCL and then feed the things we need back into CCL. This relates to the 2D power spectrum work @damonge is doing in #511

**Comment by c-d-leonard** [comment]
This issue is currently being worked on by @chrgeorgiou , first PR #739 in progress

**Comment by beckermr** [comment]
What is the plan here?

If you are going to input distances etc from CLASS or CAMB, you should know that these are being called in python now. So instead of making a bunch of new arguments to the Cosmology object, you should have a single switch that says to use the boltzmann code produced quantities.

**Comment by beckermr** [comment]
@chrgeorgiou @damonge

**Comment by c-d-leonard** [comment]
Yeah, from my understanding of what Christos is doing it's not to make a bunch of new arguments but more like a single switch like you said, but he can clarify more.

**Comment by chrgeorgiou** [comment]
The main idea of my work is to split the theory calculations and observables calculations of CCL into two distinct parts, so that if someone wants to calculate only observable quantities he can do so without having the need to define a cosmology. The ultimate goal is to be able to use CCL with the Cobaya sampler, without having to go through CCL's theory calculations. For more information you can ask David-Alonso or Antony Lewis. 

This would not change the functionality of CCL but simply extend it.

**Comment by beckermr** [comment]
I don't follow @chrgeorgiou.

**Comment by beckermr** [comment]
However, the proliferation of arguments to the Cosmology object in your PR is problematic for sure.

**Comment by damonge** [comment]
We can discuss this in detail in the next telecon, but I think this is the right way to go. We may want to create a separate constructor for cosmologies that receive distances/growth/pks directly, but I wouldn't tie things solely to the two boltzmann solvers we have right now, since the whole point of this is to make CCL cosmology-agnostic when needed.

**Comment by damonge** [comment]
(this is also off-topic with regards to the point of this issue, BTW. Christos hasn't started implementing this yet, and it will be done in a different PR).

**Comment by beckermr** [comment]
Ahhh ok. I am totally fine with creating a small number of classes, say 2, to support this.

**Comment by c-d-leonard** [comment]
@damonge would we say this issue is resolved at this point?

**Comment by damonge** [comment]
I think so. We don't need CCL to return CMB-only power spectra. There are cross-correlations we will want to compute (e.g. ISW), but those are already in the making.
