### ISSUE TITLE
Flag for slow/fast tests in C

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#498]
The code review brought up the issue that we are skipping some of our C tests due to them taking too long. We want to uncomment them but at the same time enable a flag that will allow running slow or fast tests, with Travis always defaulting to the slow one. This work is planned for the sprint week.

**Comment by villarrealas** [comment]
Limitations on ctest mean that we would likely need to subdivide things into ccl_test_example_slow.c and ccl_test_example_fast.c in order to build a fast version of check_ccl and a slow version of check_ccl.

Since we do not think that we are interested in maintaining C tests in the long term (and are looking into better python test implementation), we are closing this issue.
