### ISSUE TITLE
move ccl_gsl and ccl_splines to be allocated once per cosmology

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#504]
Right now these are global state. We should associate them with each cosmology. Then we can make them modifiable from python. We can also include the physical constants in here too. 

See these comments:
- https://github.com/LSSTDESC/CCL/pull/433#discussion_r206719385
- https://github.com/LSSTDESC/CCL/pull/433#discussion_r206677013
- https://github.com/LSSTDESC/CCL/pull/433#discussion_r206719627

Note that the last one is asking for a new integration parameter to be added to the structures above.

**Comment by beckermr** [comment]
@rmjarvis for viz

**Comment by tilmantroester** [comment]
This is a good change. One of the reasons that this was not done earlier was that not all functions take a cosmology object as an argument, which causes all kind of awkward constructs (e.g., the `ccl_splines` and `ccl_gsl` pointers you mention, the error handling system, etc).

**Comment by beckermr** [comment]
Right. We can change that too

**Comment by damonge** [comment]
One problem I see with doing this is that these objects are completely cosmology-independent, so associating them with a cosmology object (or initializing them every time) seems ugly. I'd propose an alternative, which has an added advantage:
1- One creates a NumParams (or whatever) class at the python level that contains all the information about splining, error tolerances etc. Each of these is then associated to a corresponding `ccl_splines` and a `ccl_gsl` structure in C (or a merged version of both). This would allow people to fully tune any numerical parameter in CCL.
2- We add an optional parameter to the Cosmology constructor (e.g. `num_params`). This can be either a `NumParams` object or `None`. If `None`, then the a default C structure gets created and attached to this cosmology. Otherwise, the structures associated with the `NumParams` object just get linked to the `ccl_cosmology` object.

Thoughts?

**Comment by beckermr** [comment]
Creating extra versions of these classes costs almost no time or work. I can see how it seems ugly, but the code to override the global settings with local ones has its own edge cases and issues.

It is a lot simpler and easier in my mind to simply copy in the defaults each time. As part of this, I am going to remove the params.ini files. Instead the defaults will be hard coded. People can change them after the cosmology object is made if they want to.

**Comment by damonge** [comment]
OK, as long as all parameters are easily accessible from python, I'm cool with it (just saying because sometimes this won't be transparent through the swig layer).

**Comment by beckermr** [comment]
Right. Unfortunately we have to deal with the C code first. Then we can do the python code. This is all a lot more work than it has to be. We need to deprecate the C API.
