### ISSUE TITLE
Neutrino masses error handling

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#552]
Just running:
```
cosmo = ccl.Cosmology(Omega_c=0.27, Omega_b=0.045, h=0.67, 
                      sigma8=0.8, n_s=0.96, w0=-1., wa=-0.0,
                      m_nu=0.05)
```
gets into an infinite loop that you can only `Ctrl+C` out of. This will happen whenever you pass m_nu<0.06.

1. Why is this happening? It is a bit weird that m_nu=0 is fine, but the gap between 0 and 0.06 is not. In principle people should be able to put in whatever positive neutrino masses they want, even if they're unphysical (and I'd like to understand what "unphysical" means exactly - maybe @c-d-leonard knows?).
2. In any case, it should not be possible to fall into that infinite loop. Looking at the [code](https://github.com/LSSTDESC/CCL/blob/e32b466e3583408a01835a74360ddd6a94a89ea3/src/ccl_core.c#L357), I think it should be very easy to sort that out.

**Comment by c-d-leonard** [comment]
Hmm, that's not good. I can answer (1) - "unphysical" refers to the fact that the sum of neutrino masses should, from the mass squared differences from particle physics, be either the inverted hierarchy sum (which is I forget but around 0.1) or the normal hierarchy sum (which is 0.059). So unless there is something unexpected and horribly wrong with the sum of mass squared constraints, the sum can't be below 0.059.

But regardless, we shouldn't fall into an infinite loop. I will take a look at this (or if someone else wants to, feel free, but I guess it's my fault so I can fix it).

**Comment by damonge** [comment]
OK, but leaving observational constraints aside. Is there any physical reason why neutrino masses shouldn't add up to e.g. 0.03? I think we should allow users to have such values (e.g. I could imagine wanting to make a plot that shows constraints from cosmology regardless of any other measurements).

**Comment by c-d-leonard** [comment]
Good point. I'm not 100% sure. We should probably check with someone who is more of a neutrino theory expert - @slosar do you have any ideas?

**Comment by slosar** [comment]
So, the reason is that the code tries to satisfy both the sum of masses and mass square difference from oscillation data. It can't find a solution and then it goes into an infinite loop (there is some sort of newton minimizer than jarvis, horrified at my analytical approximation implemented in 10 mins :).
When you pass zero mass it just assume threes massless neutrinos.
I think we have an option on whether to i) split the mass equally, ii)have two massless + one massive and iii) calculate individual masses based on neutrino mass difference measurements.
The reason you are seeing this is because iii) is default.
My suggested solution would be:
If you choose i) or ii), the code should just able to do ti. If you choose iii) or (use iii) as a default) and pass sum m that is too low, the code should throw an exception and advise you to use i) or ii) if you really want to go that low.
Yes?

**Comment by aferte** [comment]
Hi, I am working on it with Danielle now. 
@damonge @beckermr @slosar

**Comment by beckermr** [comment]
great - please get someone to add you to the LSSTDESC organization 
@aferte

**Comment by beckermr** [comment]
I wanted to mention that one way to improve the code might be to use the GSL root finding routines.

**Comment by rmandelb** [comment]
@aferte - insttructions here: https://confluence.slac.stanford.edu/display/LSSTDESC/Automatic+Maintenance+of+GitHub+Teams

**Comment by aferte** [comment]
One thing I don't understand: the infinite loop happens for a low sum of neutrino mass (typically <0.06eV) in the normal hierarchy. The code seems to execute ok for the inverted hierarchy in this low mass case -- where I don't think it should as the low mass bound is ~0.1eV -- so I wonder how the code actually manage to satisfy the neutrino mass difference measurements in this case?  @slosar @beckermr @c-d-leonard

**Comment by beckermr** [comment]
No idea. Bug?

**Comment by c-d-leonard** [comment]
I'll have a look and see if I can figure out what's happening.

**Comment by c-d-leonard** [comment]
Hey @aferte, I looked into this and I am not sure exactly what was going on with the inverted vs normal hierarchy, if I had to guess I'd guess that's just a weird feature in the way it's falling into the Newton's method.

I found a couple of bugs and fixed them on the fix_lowmassnu branch (we were using the wrong variable name in a check and also not returning once we'd checked the mass was too low for the given hierarchy). 

Right now, in that branch I think the infinite loop problem should be solved, however, the error message that we get when setting up a cosmology with mnu below the min value for the given hierarchy (0.059 for the normal hierarchy) is not informative from Python. This is because this error occurs in the C function ccl_create_parameters, at which point there is no cosmology object, so I can't get an error message as part of the cosmology object to be passed back to python and printed. Does anyone have suggestions on this?

**Comment by beckermr** [comment]
We have to merge the parameters object with the cosmology one or add a status to the parameters object. This plays into whether or not we deprecate the C API. These kinds of issues are also why I have been advocating so strongly to deprecate the C API.

**Comment by c-d-leonard** [comment]
Agreed, these issues keep coming up.  I'm going to make a PR with the current thing so the bug fix gets in; seems like having an informative error message may have to wait for those bigger changes.

**Comment by beckermr** [comment]
Feel free to tag me for code review!
