### ISSUE TITLE
DEP remove extra splining step in the C(ell) computation

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#553]
Right now the C(ell) computation has an extra splining step. Instead computing the C(ell) values at the requested inputs, it builds an internal grid, evaluates them at the grid points, and then interpolates o the user requested values. This is really odd and wastes time. Let's remove it.

**Comment by damonge** [comment]
It doesn't necessarily waste time (and in most cases it actually doesn't). For most purposes you'll want to evaluate the power spectrum at a fine grid of ells (e.g. all integer ells), either because you want to use them to compute correlation functions or because you need to convolve them with the bandpower window functions (i.e. even if you're doing a power spectrum measured at 10 ell-bins, you still need to deal with the binning appropriately in each of them). The point of the spline interpolator is to evaluate the power spectrum at a set of nodes that should capture the main features of the power spectrum so that interpolating over them is not a problem.

A different question is whether the default values for the spline parameters are appropriate (e.g. whether it's overkill to use linear sampling at high ell etc.). This is a power-spectrum-dependent problem, and the scheme that is currently implemented is known to work well for CMB power spectra. One thing we could to is to allow the user to specify the gridding they want to use.

**Comment by beckermr** [comment]
I am aware of this corner case. My point is that if you want to do this, then you can build your own grid and do it after you have evaluated the grid points with CCL. 

Users can already adjust the spline grid points, but we have to maintain the code that does the adjustments. 

Note that the correlation function routines *don't* do this, which is very weird.

**Comment by beckermr** [comment]
Linear spacing at high-ell is not needed for LSS. Nothing oscillates.

**Comment by beckermr** [comment]
We need to make all of this code simpler with fewer weird surprising corner cases and assumptions.

**Comment by beckermr** [comment]
I can't really emphasize that last point enough.

**Comment by damonge** [comment]
I'm pretty sure people will use the function very sub-optimally (e.g. use it to evaluate at all ells because adding 2-3 extra lines in python to do the interpolation will be annoying). I don't see the downside of keeping the splining in place but allowing people to chose their own splining nodes.
I mean, this could just be an extra array of ells that gets passed to the angular_cl function. So you'd have two of them, one that means "calculate here" and the other that means "interpolate here", with the former one having a well-educated default. If you want, the interpolating stage can be done within python (I don't care about maintaining the C API unless it affects performance).

**Comment by beckermr** [comment]
People doing things sub-optimally is their problem, not ours. Our job is to maintain code where it is clear to users what we are doing.

**Comment by damonge** [comment]
But there must be a balance between code complexity and code usability, right?
A default spline in this case simplifies the use of the code substantially in most (if not all) practical applications, and the only problem is being able to set up that spline if you want to use the default. Again, not advocating for leaving the code as it is - things could be simplified a lot on the C side and only implement the splining in python.

**Comment by beckermr** [comment]
Code is still very usable if we eliminate the splining. People are able to write a few lines. Right now we don't cache the spline at all, so we are really not doing anybody any favors.

**Comment by damonge** [comment]
Alright @beckermr , I'm gonna open a PR for this. This is my plan:
1- I'm gonna decouple the Limber integrator from angpow at the C level, and will do al the plumbing in python.
2- Power spectra will only be computed at the ells given as input.

Note that this may require some rewiring of angpow since, if I remember correctly, it does use a spline internally. Depending on how much of this lives in CCL I may or may not fix this as well in the PR.

**Comment by beckermr** [comment]
Go for it. Simpler is better always.

**Comment by damonge** [comment]
Solved by #614
