### ISSUE TITLE
remove angpow

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#571]
Right now the code that integrates angpow with CCL is stored in an unmaintained repo with a copy of angpow in it. This is really weird TBH and also means our copy of angpow is not getting bug fixes (!).

@damonge also mentioned that there are better methods for doing what angpow does

I vote we remove it.

**Comment by tmcclintock** [comment]
For reference, I think the method that @damonge is referring to is [this paper](https://arxiv.org/abs/1807.09540), which claims to speed up Cls by a factor of 400 compared to Limber (which it gets rid of). This is apparently already implemented in CLASS, so it could be a matter of copying things over.

**Comment by elisachisari** [comment]
At the moment, angpow is the only method we have that produces non-Limber predictions. I'm in favor of discussing this, but I suggest we don't remove it till we have a good working alternative. Also, we should hear from the angpow developers what their plans are regarding maintenance of the package and synergy with CCL. I think the unmaintained repo is only there because there were some initial integration problems related to the installation process, but it might be possible to solve those instead of removing it. @jeremyneveu might want to comment on this.

**Comment by jeremyneveu** [comment]
Hi all. Angpow is in a separate repo because I was asked to do so (in order not to mix c++ and c files), but I would have been in favor to fully integrate it in CCL. There is also the issue to maintain the link with the original and maintained Angpow version there https://gitlab.in2p3.fr/campagne/AngPow . 

The paper pointed by Tom provides a fast way to compute non Limber Cells, much faster than the previous CLASS computation but the latter was very very long. So in final it is not sure that this code is faster than Angpow (but I guess it is) and it is not public yet. I would be in favor that the two methods are in CCL and cross-benchmarked before making a decision. I think that the new CLASS method is probably better, but the spirit of CCL is that codes are compared and tested so let's test them before removing Angpow.

Concerning the maintainance this Angpow4CCL repo, I am not a fluent coder in c nor c++, and even less for the interfacing  between the two languages. I would greatly appreciate some help to make a better interface between CCL and Angpow if you think the way it is done currently is probematic. I need to talk to the other Angpow developers too.

**Comment by beckermr** [comment]
Thanks for the context! 

We could maintain the file that interfaces ccl locally and compile it into angpow. 

I’m still in favor of deprecation here but we don’t have consensus.
