### ISSUE TITLE
graceful neutrinos at low masses

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#572]
We should allow neutrino mass sums less than 0.06 by switching to one massive and two massless. This would happen when doing computations with the normal hierarchy.

**Comment by c-d-leonard** [comment]
A couple of us (@sjoudaki @elisachisari) were chatting about this so I'll summarize what we discussed here:
- the normal hierarchy and inverted hierarchy only make sense within the context where we are incorporating information from experimental particle physics constraints; that's where the hierarchies come from.
- you could argue then that if you are using the normal hierarchy setting for neutrino masses, to be consistent, you would have to include a hard prior that the sum of masses not go below 0.06, because below this value the normal hierarchy is meaningless (one of the masses must be negative)
- if we are talking about cosmology-alone constraints, it probably doesn't actually matter how you split the masses ever (but we're not 100% sure this is true), so if so it would be fine to just use a single massive neutrino with the full sum of masses from the get go; this would easily allow us to consistently go below 0.06 in a chain.
- if we imagine doing some joint probe constraint with particle physics at some point, then it would matter how we split the masses, and it would be important to be able to go below 0.06 somehow for chains. I don't know if this is something we care about supporting and I don't know how to deal with this without negative masses.
- if we do something simple like allow the normal hierarchy to dictate the masses down to 0.06 and then switch to a single masses we will have discontinuities in the masses we may want to worry about.
@christianel @slosar @dodelson @damonge and anyone else who cares, it would be good to get your takes on this.

**Comment by beckermr** [comment]
No matter what we neee to not have infinite loops. I’m in favor of a single massive species as a named option actually. We could call it ‘single’ or something. 

I cannot speak to the physics here except that if we are actually incorporating external data, it should be done in the form of a product or likelihoods, not in terms of hard coded constraints in C.

**Comment by slosar** [comment]
@c-d-leonard You are not quite write at the last point, as sum mnu->0.06 from above the normal hiearchy constraints put all mass into one and makes have m->0. So the change-over to single mass scheme is continous and I also think continous in the first derivative (i.e. the other two masses quadratically approach zero, although one would need to check this). In any case, no discontinuities there. For inverted hierach, the masses go to two equally massive of at 0.11eV (or whatever) and one massless in a similar fashion.
@beckermr Re  your second point: true in principle, but irrelevant in practice. Within our precision, the delta m^2 are known with effectively infinite precision (i.e. we also don't incorporate the value of proton mass, etc.  through likelihood)

**Comment by sjoudaki** [comment]
Hi Anze, the change-over to single mass scheme would indeed be continuous in the sum of the masses, but not in the individual masses. But, it's more of an "aesthetic" note.

**Comment by slosar** [comment]
@sjoudaki Ok, fine, perhaps not mathematically, but for all practical purposes yes. See e.g. Fig 3 of https://arxiv.org/pdf/astro-ph/0604335.pdf, the correction is less than 0.01eV, so the second heaviest neutrino is still more or less relativistic today. 
(But now I admit this is much bigger than I thought it would be, it is O(10%) correction))

**Comment by beckermr** [comment]
Good to know @slosar. I am not familiar with how well these mass differences are known. Thanks!

**Comment by sjoudaki** [comment]
@slosar I agree that the impact is small, hence the reference to aesthetics as the main benefit of avoiding discontinuities in the individual masses :)

One paper that may be relevant to the broader discussion of whether we are at all sensitive to how mass is assigned to neutrinos is arXiv:1003.5918, which given the survey properties considered, seems to support the views here (that we are unlikely to be sensitive to the specific mass assignment scheme). But could be useful to carry out an updated analysis with LSST survey properties and realistic systematics treatment at some stage.

**Comment by slosar** [comment]
Ok, so perhaps drop this weird scheme and just stick with a named "single" scheme. Alternative is to lower change one splitting so that lower mass is allowed, but that is perhaps even uglier.

**Comment by beckermr** [comment]
Sounds good to me @slosar. We need to cleanup the infinite loops in this code so all of this can be done in one pass.

**Comment by sjoudaki** [comment]
Yes, also sounds fine with me.

**Comment by c-d-leonard** [comment]
- Definitely yes we need to get rid of infinite loops. 
- To make sure I understand: is the plan we seem to be converging on that we add a named option for a single mass as well as keeping the hierarchy options as-are (modulo fix infinite loops)? Do we want to keep the normal hierarchy option as default or do we think the single mass option should be the default?

**Comment by dodelson** [comment]
not sure i followed all this, but this is what i would think would be optimal: take the lightest mass and the hierarchy as the 2 free parameters (one continuous and one discrete, but I think Joe said discrete parameters are possible (if not, you can do 2 separate chains)). With these two parameters, the other 2 masses and therefore the sum of the 3 is fixed by particle physics \Delta m^2. You could decide whether the chains need to be run with the full set of 3 masses (not very difficult in most codes, i don't think) or shoving them all in one is ok. I would think it would not be when combining with CMB data, but not sure

**Comment by beckermr** [comment]
Yes @c-d-leonard. I think we keep the current defaults. 

@dodelson This procedure sounds great. Discrete params are possible with some MCMC codes. However, I think this suggestion goes beyond the scope of this particular issue and is related to how we are using CCL as opposed to what CCL supports.

**Comment by elisachisari** [comment]
This is a report on progress on this issue. The "infinite loop" was addressed in PR #605 but from the above discussion we would still want to implement a "single mass" option for neutrinos instead of passing (M,0,0). I an opening another issue to address that.

**Comment by beckermr** [comment]
Any neutrino officianados from this issue willing to look at how I am calling CAMB versus CLASS here: https://github.com/LSSTDESC/CCL/pull/677?
