### ISSUE TITLE
better angpow integration

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#584]
We have decided to revisit the angpow integration and remove the intermediate repository. The code to wrap the C++ for C should either be moved to CCL or to the upstream repository. I forget which we decided is better, but let's get that discussion in writing here. 

@jeremyneveu for viz

**Comment by jeremyneveu** [comment]
Dear all,
I talked with Jean-Eric Campagne @jecampagne the possibility to improve the Angpow intergation in CCL. We agree that the current situation is not satisfactory. We propose the following steps to go forward:
1. create a new branch in CCL for this development (of course...) and migrates there the interface files currently in Angpow4CCL (there is no point in putting these files in the original Angpow repo as we can't compile them without CCL)
2. Angpow maintained version is currently on gitlab: create a mirror repo on the LSSTDESC github repo
3. modify the cmake/setup to point to this mirror and compile the latest version of Angpow (@EiffL can you help on this ?)
4. develop the interface and benchmark again.
5. when all is approved, delete the Angpow4CCL repo.
Jean-Eric has also talked to @damonge who agrees with this plan and would like to have a look (thanks David !). We also checked that it would be better that Angpow is called via CCL only for the non-Limber computation in order to maintain only that kind of computation whatever the evolution of CCL. @beckermr do you agree ?

**Comment by beckermr** [comment]
Sounds good. One question. Do we need the mirror or can we have the cmake build download a release directly from gitlab?

**Comment by jeremyneveu** [comment]
We can first try without the mirror and see if we like it.

**Comment by jeremyneveu** [comment]
Hi,
I just pushed a new branch angpow4ccl that contains in src/ and include/ the interface files that were inside the Angpow4CCL repo. So step1 is done, can someone have a look to step2/3 ?

**Comment by damonge** [comment]
@jeremyneveu : it'd be worth thinking about whether and how angpow could deal with the new refactoring of the C_ell implementation being discussed in #627

**Comment by beckermr** [comment]
I removed the v2 milestone here. We can add this back without breaking the API.

**Comment by c-d-leonard** [comment]
This issue is obsolete at this point, I'm going to close it.
