### ISSUE TITLE
Omega_m does not contain neutrinos

### ISSUE THREAD

**Issue by slosar** [LSSTDESC/CCL#647]
It just came to my attention that our Omega_m does not contain neutrinos.
I think this goes against standard convention in which Omega_m does contain massive neutrinos assuming they are fully non-relativistic and which is followed by at least Planck and BOSS papers (would be good to check, but I am 99% sure this is the case, because I remember fighting this cause on the "no neutrinos in Omega_m" side (let's call it yellow) and was convinced otherwise for Auburg et al BOSS paper). 
This would be an annoying break with the past, but on the other hand following different convention than Planck is also very dangerous. 
This should be at minimum discussed and clearly documented.
@damonge

**Comment by damonge** [comment]
I don't oppose to this, but I'm curious what the reasons were to make you think that putting neutrinos in Omega_m was a good idea. I would have thought, because neutrinos are not an "a^-3" species for some of their evolution, they would deserve their own Omega.

If we put them as part of Omega_m, should we do that at all times? Or only after they become non-relativistic? How exactly should we define that time?

**Comment by slosar** [comment]
The meain reason was convention. I don't want someone to read of Omega_m from Planck's paper, plug it in CCL and get just annoying different results. Because including it or not does make a significant differentce at the level of Planck likelihood.
Note that for low redshift z<6, massive neutrinos do behave essentially as 1/a^3, so including them is a better approximation. But at the end of the day, Omega_m is just a label, i.e. you have Omega_m=Omega_b + Omega_cdm + Omega_numass and with sufficient other constraints you can solve for all 3 individually. So fundamentally it is parameterization, not physics.
