### ISSUE TITLE
Signalling parameter-dependence of functions and validity of parameter values

### ISSUE THREAD

**Issue by philbull** [LSSTDESC/CCL#68]
As models and cosmological parameters are added beyond vanilla LCDM, it will become necessary to signal which functions support certain new parameters, and which values of those parameters are valid. This could be done through documentation alone, but it would be more robust if the CCL code was able to perform validity checks itself.

Being able to check which parameters are supported/required by a function would also be useful for likelihood/sampling codes, which can use this information to define fast/slow parameters, or to cache the results of expensive calculations. Monte Carlo analyses that propose invalid values should also be given enough information to fail gracefully.

The following types of test are likely to be useful:
1. Whether a function depends on a given parameter (e.g. H(z) does not depend on sigma_8)
2. Whether a parameter or certain parameter values are supported by the function (e.g. does the function assume Omega_K = 0?)
3. Whether the parameter value is in a physically valid range (e.g. negative h)
4. Whether the parameter value is in a range that has been validated for precision (e.g. the mass function is unlikely to be accurate for n_s = 2)

The results of some of these tests may be conditional on the values of other parameters (e.g. degraded precision on parameters derived from the power spectrum when w != -1, Omega_K != 0).

While these tests could be hard-coded in each function, e.g. using assertions, this will significantly increase the maintenance burden and complexity of the code as new parameters are added. Ideally, a simple, low-maintenance way of enforcing validity conditions on parameters and functions would be incorporated into the API.

**Comment by c-d-leonard** [comment]
@philbull do you think this is worth keeping open?

**Comment by damonge** [comment]
OK, last chance! We'll close this in a few days unless someone tells us not to!

**Comment by nikfilippas** [comment]
I don't think this is needed (or can be implemented) at this point as it will unnecessarily complicate the codebase, checking every parameter separately. This would also go against the "consenting adults" paradigm of code-style. Users should be free to pass whatever they want as long as it makes sense to them. Additional parameters checks etc. can be implemented at the likelihood level, but not in CCL.

Closing now since more than a few days have passed since 5 Aug 2022.

**Comment by nikfilippas** [comment]
I don't think this is needed (or can be implemented) at this point as it will unnecessarily complicate the codebase, checking every parameter separately. This would also go against the "consenting adults" paradigm of code-style. Users should be free to pass whatever they want as long as it makes sense to them. Additional parameters checks etc. can be implemented at the likelihood level, but not in CCL.

Closing now since more than a few days have passed since 5 Aug 2022.
