### ISSUE TITLE
Theorist-level observables: Clusters

### ISSUE THREAD

**Issue by elikrause** [LSSTDESC/CCL#7]
- [ ] cluster number counts, without mass-observable relation complications
- [ ] cluster number counts, binning by observable mass proxy
- [ ] cluster lensing power spectra

**Comment by villarrealas** [comment]
@tmcclintock has volunteered to work magnification and shear profiles for the cluster weak lensing calculation into CCL. These routines will be necessary for cluster weak lensing.

I believe he intends to work on it from this starting point: https://github.com/tmcclintock/Cluster_WL

**Comment by tmcclintock** [comment]
Looping back to this. I vote to overhaul this issue and make it about implementing halo related theory code. Is this OK with the powers that be, or would it be better to scrap this issue and make a new one entirely? @elisachisari @beckermr 

For what it's worth, the first two bullet points that @elikrause wrote here would exist in a place like firecrown (since they would involve integrals over observables, not just a "theory" quantity like mass), so it would make sense to start an entirely new list for halo science. Some of the things that would go into a new list would include: halo density profiles, halo correlation functions, halo lensing power spectra, projected halo profiles (e.g. Sigma(R), DeltaSigma(R), kappa and gamma), HODs, mass-concentration relations, mass definition conversions (e.g. 200m - vir).

I would be happy to lead the development on this at the February meeting.

**Comment by beckermr** [comment]
Yes I agree with @tmcclintock and @elikrause and I have already discussed exactly this course of action. Closing.
