### ISSUE TITLE
Write yaml function doesn't output TF/power keywords

### ISSUE THREAD

**Issue by elisachisari** [LSSTDESC/CCL#711]
If I try to export this cosmology to a yaml file with CCL as follows
`cosmo = ccl.Cosmology(Omega_c=0.25, Omega_b=0.05, sigma8=0.8, 
h=0.7,n_s=0.96,baryons_power_spectrum='bcm')`
`cosmo.write_yaml('example_params.yaml')`
the last part `baryons_power_spectrum='bcm'` won't be saved. 

We need to be able to read/write transfer function, baryons and power spectra options so we can pass them around if needed.

**Comment by c-d-leonard** [comment]
@joezuntz I think you wrote this functionality originally - any change you have time to make this change? no worries if not.

**Comment by joezuntz** [comment]
It might be worth thinking more about this whole functionality - I only ever wrote it to solve a short-term need in TXPipe, and I always thought it could do with an upgrade. I don’t think I’ll have time, but any changes would be fine on my end.

**Comment by c-d-leonard** [comment]
Hmm okay, thanks. What's the status for interacting with TXPipe now, is the yaml functionality still required at this point?

**Comment by joezuntz** [comment]
Yes, something is needed - I need something to be able to read the parameters that specify a cosmology from a simple file, and use it for when I need a fiducial cosmology.  One issue, though, is that this really needs to also specify a complete nuisance model, too, since what we really want is a complete fiducial model for the data vector.

So maybe TXPipe should be calling FireCrown instead?

In case useful, here are the places we use this right now:
- when making plots showing theory vs data
- when generating fake maps to test with
- when making an analytic covariance
- in NaMaster when projecting out modes

**Comment by c-d-leonard** [comment]
Hmm, okay, thanks. Yeah, if you need nuisance parameters and cosmological parameters in the same place firecrown might make more sense. But I'm guessing this is not something to be tackled immediately so we can leave this open for the moment.

**Comment by tilmantroester** [comment]
This should be addressed now with #852, #854 (i.e., all arguments to `Cosmology` get written and read to/from yaml).

**Comment by c-d-leonard** [comment]
@joezuntz are you happy with this being resolved?

**Comment by joezuntz** [comment]
Yep, looks great - many thanks.
