### ISSUE TITLE
Correlation function docs are equivocal

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#740]
![corr](https://user-images.githubusercontent.com/8809493/76547479-23aa1b00-6485-11ea-85ba-438c466a852f.png)

The above should explain that this is not specific to galaxies or shear, but general for any spin-0 or spin-2 fields respectively.

**Comment by rmjarvis** [comment]
With some humility, I might suggest following the TreeCorr convention?  N for counts, G for shear, K for kappa.  

So the above would be NN, NG and GG.  GG produce two outputs, xip and xim, so you could add a + and - if you want to distinguish them.  But since TreeCorr is relatively widely used at this point, it seems prudent to not reinvent an entirely different naming scheme.

**Comment by damonge** [comment]
Thanks @rmjarvis 
I thought about doing something like this, but I decided against it to avoid triggering a new version by changing the API. I'll open an issue about this.

**Comment by rmjarvis** [comment]
There are ways of doing this without triggering an API change.
The most straightforward is to deprecate this kwarg and make a new kwarg that implements the new naming scheme.  E.g. simply `type` (since `corr_` is probably redundant for an argument to the function `correlation`.
Then the first thing the code does is
```
if corr_type is not None:
    if corr_type == 'GG' : type = 'NN'
    elif corr_type == 'GL': type = 'NG'
    elif corr_type == 'L+': type = 'GG+'
    elif corr_type == 'L-': type = 'GG-'
    else: raise ValueError("Unknown corr_type")
    depr_warn("corr_type is deprecated.  Use type = {}".format(type))
```
Where depr_warn would raise a deprecation warning in whatever way you have set up to do that.

**Comment by damonge** [comment]
OK, done
 @rmjarvis can you review this one: https://github.com/LSSTDESC/CCL/pull/741 ?

**Comment by rmjarvis** [comment]
Did you push?  I'm still just seeing the corr_type doc change there?

**Comment by damonge** [comment]
sorry, my internet is a bit laggy. It's there now.
