### ISSUE TITLE
cache calls to boltzmann codes

### ISSUE THREAD

**Issue by beckermr** [LSSTDESC/CCL#809]
We can use LRU caches to cache calls to boltzmann codes. 

The task is to refactor the internals of the functions to extract the info they need from the Cosmology object in one step, make this info into something that is hashable in python, and then write the rest of the function to take this info and call CAMB. We then put the cache on the internal function. 

firecrown caches CCL calls already and can help serve as an example. See here: https://github.com/LSSTDESC/firecrown/blob/master/firecrown/cosmology.py

We probably need to do better on building specialized LRU caches that understand floating-point behavior etc.

cc @damonge @EiffL

**Comment by damonge** [comment]
I think this is interesting but I'd like to understand the logic for doing this in CCL rather than downstream.

Am I right that you'd like then for the CCL cosmology object to be dynamical after being initialized? I.e. that you could change Omega_c and it would then realize that it needs to call camb again?

Since this is by far the dominant time sink when initializing the cosmology, why is it better to do this within CCL rather than firecrown  or anything else on the likelihood side that just creates a new cosmology?

**Comment by beckermr** [comment]
A CCL cosmology's parameters are fixed once they are instantiated. What this does is make it so that if you are making a bunch of them at the same cosmology, you don't have to rerun the boltzmann code. 

It is not so much that it is better or worse, but that this optimization is simple to support and help users generally.

**Comment by beckermr** [comment]
Also, the boltzmann code is not run when the cosmology is created. It only gets run when you actually need something it computes.

**Comment by damonge** [comment]
So you mean, if you have many instances of the same cosmology, CAMB only gets called once, right? In what situations is this useful? (honestly asking!).

> Also, the boltzmann code is not run when the cosmology is created. It only gets run when you actually need something it computes.
Yep, yep. What I meant to say is that the main thing in getting P(k) or C_ell is calling camb, not actually initializing the CCL cosmology

**Comment by beckermr** [comment]
It's useful anytime someone happens to instantiate the cosmology the same way again. Automatic caching systems like this can ease the burden for downstream developers. For example, with this change I would not need to have the caching in firecrown and other users would get the caching for free.

**Comment by vitenti** [comment]
I don't know if I understood correctly the idea, but I would be careful with caching, this usually interacts badly with a MCMC sampling. In this case there is a large number of calls to the Boltzmann code with different parameters, thus, the cache grows very large and the cache search can add a significant overhead. Moreover, there is little use in this case, the probability of two steps with same parameters is almost zero (unless there is a fast-slow sampling).

**Comment by beckermr** [comment]
The lru caches have a maximum size. 

We can map similar cosmologies into one another at the level of precision we care about.

**Comment by nikfilippas** [comment]
@damonge I can see this saving loads of time when doing tomography. Suppose for example, that we are interested in seeing how the power spectrum changes within a single bin, for different cosmologies. Coding-wise, it makes sense to put the redshift bins in the outer loop, but under the current implementation, this would be extremely slow, so the user would either have to save the cosmologies for later use downstream, or create a multi-dimensional empty array to store the values of the power spectrum (instead of dumping them right after the z-loop is done).

This won't benefit any MCMC for the reasons Sandro mentioned; just the simple everyday use of CCL when producing plots for example. It's easy to implement too, I can give it a go.
