### ISSUE TITLE
CCL crashing when trying to compute tangential shear for sources in front of lenses.

### ISSUE THREAD

**Issue by jpratmarti** [LSSTDESC/CCL#811]
Hi,

I've noticed that when all sources are in front of the lenses CCL gives this error:

```
double free or corruption (!prev): 0x0000555556df0eb0 ***
Fatal Python error: Aborted
```
In general we might just want CCL to return zero instead of crashing? This could be useful when running FireCrown with a sacc file that contains several lens and source bins, and some of the lens-source combinations fall into this category (probably will only happen when binning in truez in simulations).

**Comment by jpratmarti** [comment]
Just to be clear, I actually got this error when running firecrown, so I'm not completely sure where it's coming from.

**Comment by damonge** [comment]
I can't reproduce this error. With this code:
```
import pyccl as ccl
import numpy as np
import matplotlib.pyplot as plt


cosmo = ccl.CosmologyVanillaLCDM()

numz = 1000
z = np.linspace(0.0, 3.0, numz)
nz_all = z**2*np.exp(-(z/1.2)**1.5)
nz_lens = nz_all.copy()
nz_lens[:550] = 0
nz_source = nz_all.copy()
nz_source[450:] = 0
bz = np.ones_like(z)
plt.plot(z, nz_lens, label='Lenses')
plt.plot(z, nz_source, label='Sources')
plt.legend(fontsize=15, loc='upper right')
plt.xlabel('$z$', fontsize=15)
plt.ylabel('$N(z)$', fontsize=15)
plt.show()

ls = np.unique(np.geomspace(2, 1000, 20).astype(int)).astype(float)
tg = ccl.NumberCountsTracer(cosmo, has_rsd=False, dndz=(z, nz_lens), bias=(z, bz))
tl = ccl.WeakLensingTracer(cosmo, dndz=(z, nz_source))
cl = ccl.angular_cl(cosmo, tg, tl, ls)
plt.figure()
plt.plot(ls, cl)
plt.xlabel(r'$\ell$', fontsize=15)
plt.ylabel(r'$C_\ell$', fontsize=15)
plt.show()
```

I get the disjoint N(z)s:
![nzs](https://user-images.githubusercontent.com/8809493/183122856-2214d6be-f2b7-4ae5-a156-fc67e804743c.png)

The corresponding C_ell gets calculated and is 0 (as it should) without any errors
![cl](https://user-images.githubusercontent.com/8809493/183122893-f2c22db3-5473-4d5b-868f-34fc3423b6d4.png)

This might be because firecrown was using an old version of CCL or because this has been fixed since the issue was raised (2 years ago!).

I'll close, but please reopen if the issue remains.
