### ISSUE TITLE
Correlation function calculation at small angular separation

### ISSUE THREAD

**Issue by TiankeZhuang** [LSSTDESC/CCL#826]
Hi, I'm working on a project which involves measuring the dark matter distribution in galaxies using data from the HSC survey. My advisors, Professor Rachel Mandelbaum, and Simon Samuroff suggested that I perform a preliminary fitting on the lensing and clustering correlation functions using CCL and I ran into a problem generating these functions at angular separation scales around 10^-2 degree. 

Following [this](https://github.com/LSSTDESC/CCLX/blob/master/CellsCorrelations.ipynb) notebook, if I change `theta_deg` under In[8] to `theta_deg = np.logspace(-3, np.log10(5.), 40)`, I get the following plots for the lensing and clustering correlation functions:
![lensing](https://user-images.githubusercontent.com/34909348/98302620-bb1b2b80-1f8a-11eb-90c8-1c80b33914ce.png)
![clustering](https://user-images.githubusercontent.com/34909348/98302624-be161c00-1f8a-11eb-9114-13479ce0f5a8.png)

Are there any changes that I could make to improve the accuracy of correlation calculation at angular separation scales around 10^-2 deg? Thank you!

**Comment by damonge** [comment]
@TiankeZhuang with apologies for the huge delay, here's the solution. At the very top of your script, you need to update the precision parameters of CCL so that the integrals are stable down to such small scales:
```
ccl.spline_params.ELL_MAX_CORR = 10000000
ccl.spline_params.N_ELL_CORR = 10000
```

This will give you 
![corrs](https://user-images.githubusercontent.com/8809493/183128597-4eaa3843-ee3e-4d5e-a803-31b8bfc23d06.png)

To be honest, I don't like these variables not being evident through the correlations API, so we may want to change that in the future. At the very least we need to document this better.

**Comment by rmandelb** [comment]
Thanks @damonge .  Tianke graduated and is no longer working on this project, but it's good to know CCL does have knobs to turn for this purpose.  Documenting it better would be beneficial, I think.

**Comment by damonge** [comment]
Thanks @rmandelb and very sorry we didn't address this sooner!
I've tried to do that in #974, if anyone cares to review.

**Comment by rmandelb** [comment]
Thanks!
