### ISSUE TITLE
Note compilation in CI

### ISSUE THREAD

**Issue by damonge** [LSSTDESC/CCL#850]
We removed the unit test that compiled the CCL note because it often failed due to errors finding one of the many dependencies needed. We should fix this and bring it back if we think we need this check.

**Comment by carlosggarcia** [comment]
I think this is related to the error I am finding in the TJPCov CI:

```
      CMake Error at cmake/Modules/FindNumPy.cmake:71 (list):
        list GET given empty list
      Call Stack (most recent call first):
        pyccl/CMakeLists.txt:9 (find_package)
```

For now, it is not a problem because it then uses `setup.py install`. However, there is this deprecation warning:

```
DEPRECATION: pyccl was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 23.1 will enforce this behaviour change. A possible replacement is to fix the wheel build issue reported above. Discussion can be found at https://github.com/pypa/pip/issues/8368
```
For now, I am installing `numpy` before CCL (which for some reason starts compiling before installing its dependency).
