### ISSUE TITLE
Problem installing CLL with Conda

### ISSUE THREAD

**Issue by dlanzieri** [LSSTDESC/CCL#873]
I want to bring several issues I had when I tried to install CCL with Conda. 
In my `base` environment, I used the command:

> $ conda install -c conda-forge pyccl

and I got the following error (I show only the first part):

> Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for pytest nltk astropy anaconda: : 308it [1:03:38,  

followed by about 300 pages of conflicts.
So, I tried installing CCL by using  `pip`.  In order to do this, l needed `CMake` installed on my system.
I used the command :

> $ conda install cmake

getting the following:

> EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /opt/anaconda3
  uid: 1314976754
  gid: 2048330233

Therefore, I thought to activate my `conda` environment ([here](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) to create a new Conda environment ) and install CLL in it.
By using 

> $ conda install -c conda-forge pyccl

 again got problems of conflicts .
So, I tried by using `pip` and after installing missing dependencies:

> $ conda install cmake

and 

> $ conda install fftw

and 

> $ conda install swig

the command 

> $ pip install pyccl

worked!

**Comment by EiffL** [comment]
Thanks for reporting this @dlanzieri ! I have a small question, I'm not sure I understand the middle of your post, you say:
```
$ conda install cmake

getting the following:

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
environment location: /opt/anaconda3
uid: 1314976754
gid: 2048330233
```
Do you mean that the conda install cmake is giving you that error? or that after installing cmake, you try to pip install pyccl and get that error?

**Comment by dlanzieri** [comment]
Hi @EiffL you're welcome ! :) 
The first one, 

> $ conda install cmake

 gives me that error.

**Comment by c-d-leonard** [comment]
Thanks for documenting this! I'm not sure if we should consider this an open issue at this point since you were eventually able to install - @EiffL what do you think?

**Comment by EiffL** [comment]
Well... essentially, I think there are 2 interesting things here:
- Why is the conda install not working? I have absolutely no idea. Matt might know
- If conda can fail, should we have some documentation to explain how to do a pip install? So that if someone has the same problem as Denise, they would be able to find an answer somewhere.

**Comment by nikfilippas** [comment]
I use anaconda for all the Python things.

In most cases, the `pip` version which is installed in the system is different to the `pip` version in the anaconda environment. There's normally a `/usr/bin/pip` and a `anaconda3/bin/pip`. These two are different and it's bad practice to mix the two because this can cause conflicts in the future (if, for example, PYTHONPATH points to two packages of the same name in different environments).

Noting that you don't have write permissions I assume you are using a shared computer where you're not an admin. Most of these have cmake pre-installed for every user. What you probably lacked was cmake in your own conda environment. So I think if you tried `pip install` this would have worked right away.

To be on the safe side though, you'd have to do `anaconda3/bin/pip instal` in order not to mix up different Python environments.
The astropy conflict that you were getting must have been due to healpy's requirements.

**Comment by damonge** [comment]
I will close due to lack of activity. Please reopen if this is still an issue.
