### ISSUE TITLE
foolproof+futureproof cosmology instantiation

### ISSUE THREAD

**Issue by nikfilippas** [LSSTDESC/CCL#878]
Currently, CCL cosmology objects can be instantiated without passing any keyword-arguments, like so:
`ccl.Cosmology(0.25, 0.05, 0.65, 0.96, 0.81)`. If for some reason the ordering of arguments in CCL changes in the future, then codes built without explicitly declaring the parameters passed will silently fail, giving the wrong cosmology.

We can make all arguments passed in cosmology to be keyword-only. This way, the user must explicitly state which parameter is which, and this is also futureproof in case the ordering changes and/or more parameters are added.

This is easily done by adding the `*` operator after the `self` argument in every cosmological `__init__` method.
Then, if the user tries to pass in just numbers without keywords, the code will exit with the following message:
```
TypeError: Cosmology() takes 1 positional argument but 6 were given
```

This thinking can be extended to any class method that takes in a number of parameters to update (for example halo profiles), but I think it's more important to do it in `ccl.Cosmology_functions()` first.

**Comment by rmjarvis** [comment]
+1 on this.  This is a really nice feature they added in python 3.  I haven't used it much yet in my own code, since I've still been supporting 2.7, but that's done now.  So I'll be adding this to most of my functions pretty soon.

I think a rule of thumb that will usually work is if the first argument is strongly implied by the name of the function, then let that be keyword-less.  E.g. `readFile(file_name)`.  But then anything after that should be keyword-only.  (Indicated by adding the `*` as Nick mentioned).  For functions that don't have an obvious-from-context first argument (like `Cosmology`) make everything keyword-only.

This makes for much more readable user code, so you're really helping your users out by adding this to help them make their own code better.  `ccl.Cosmology(0.25, 0.05, 0.65, 0.96, 0.81)` is pretty cryptic compared to `ccl.Cosmology(Omega_c=0.25, Omega_b=0.05, h=0.65, ns=0.96, sigma_8=0.81)`.  You're doing your users a favor forcing them to use the latter.  :)

**Comment by damonge** [comment]
@rmjarvis would this count as a change to the API and thus trigger a new release?

**Comment by rmjarvis** [comment]
It's arguable.  But personally I'd be happy to let it go as a minor release, not a major one.  It's definitely not a bugfix though.  :)

**Comment by nikfilippas** [comment]
@rmjarvis I would personally be slightly more lenient than that rule of thumb you mentioned. CCL is made to integrate well with Python code, and in most cases, the **variable names we give are very similar to the argument names of the CCL functions**.

Ideally, users would have to explicitly state the used model's parameters in order to avoid mix-ups and write futureproof code (like I mentioned in my first post), but we'd like to avoid things like:
```
ccl.foo(cosmo, k=k, a=a, dndz=dndz, method='no_idea')
```
or even:
```
ccl.foo(cosmo, k=k_arr, a=a_arr, dndz=nz, method='no_idea')
```
So in the previous example, I'd probably put the star before the `method` argument.

Also, private functions don't necessarily need to include the the star (although practically in Python nothing is private).

PS: In newer Python versions, there's also the `/` operator which separates positional-only arguments from the rest. But this is redundant I think, there's no reason to prevent users from using `ccl.foo(cosmo=my_cosmo ...)`.

If there's a consensus on this from the collaborators I could go through the entirety of the Python code and make the appropriate changes.

**Comment by rmjarvis** [comment]
It's up to you of course.  I'll just remind you that code is read far more often than it is written.  So you should prioritize making things clear to readers over making it easy for writers.

**Comment by nikfilippas** [comment]
I see. Taking into account the stuff with the API change that you discussed with David, I think only adding a star where most people would have declared the argument names would be fine for now.

Being stricter and, for example, changing
`def omega_x(cosmo, a, species)` to
`def omega_x(cosmo, a, *, species)`
would probably break many codes that use
`omega_x(my_cosmo, 1., "matter")`
and that would borderline count as too much change for a minor release.

So I'll do all the "necessary" changes and I'll leave the rest for the next major release. :)

**Comment by rmjarvis** [comment]
FYI, I found a way to add the kw-only bit while maintaining backwards compatibility if you want to care about that.

https://github.com/flying-sheep/legacy-api-wrap

It's a decorator that lets you add the * to your signature, and then if the user treats any kwargs as positional, then they get a deprecation warning rather than a TypeError.

**Comment by nikfilippas** [comment]
Thank you, Mike. This could be useful if we don't want to change the API, but:

- it would trigger so many warnings that the output of the run would be a complete mess, so the users would be forced, in a way, to make the changes (like in the cases where an error is thrown), OR
- the users would mute warnings, in which case we fall back to the first issue.

Together with @damonge I've collected my thoughts on this in a more clear manner. I'm closing this and I'm opening a new, more to-the-point issue.
