### ISSUE TITLE
Should global settings live outside of the cosmo object?

### ISSUE THREAD

**Issue by nikfilippas** [LSSTDESC/CCL#885]
Currently, we need access to the `cosmo` object to query some parameters which are not directly related to cosmology.

Here's an example showcasing this:
`Pk2D` accepts either (i) a user-sampled P(k,a) [`lk_arr`, `a_arr`, `pk_arr`] or (ii) a function which produces the P(k,a) array [`pkfunc`]. In the second case, a `cosmo` object needs to be passed, just so the global spline sampling parameters are queried. Cosmology itself is not used at all. In practice, one could initialize a `cosmo` object with *any* set of parameters and pass it into `Pk2D`, because the only thing needed is the spline parameters (queried from `cosmo`).

I think this is a slightly awkward use of `cosmo`. It might give users the impression that the cosmological parameters are of some importance here, while in reality, they are not.

We can fully detach the CCL settings from `pyccl.Cosmology` (and possibly make them settable via something like `ccl.PARAM_SET(0.3)`), so that functions and methods that need them won't have to require that a random cosmology object is instantiated.

**Comment by nikfilippas** [comment]
This might also break some API (if we're going to change `Pk2D` and the like, for example), so it probably also needs tagging for v3.

**Comment by tilmantroester** [comment]
On the C-level, the cosmology struct is the catch-all for data that is being passed around: accuracy parameters, cosmological parameters, error messages, etc. This isn't great but changing it would involve a lot of work. Presumably you could write some wrappers on the Python-level that create dummy cosmology structs based on just some subset of the data that is actually needed. But then this needs to be tracked carefully so that these dummy cosmology objects aren't used for anything else.

**Comment by nikfilippas** [comment]
I am not very familiar with the inner workings of CCL in C, so this might be a naive question, but couldn't this data be passed around via a GLOBAL_SETTINGS script, as is currently done with the global constants?

**Comment by tilmantroester** [comment]
Which global constants? Almost everything should (hopefully) live in structs that can be passed around.

**Comment by nikfilippas** [comment]
So all the parameters [here](https://github.com/LSSTDESC/CCL/blob/17889df6a4f213d0048df77d9b6085fbbd9cb0fb/src/ccl_core.c#L101) live in the struct that is in `cosmo`?

**Comment by damonge** [comment]
I think the same way we have something like `ccl.physical_constants.CLIGHT`, we should have `ccl.spline_params.NK_PK` or whatever. I think it doesn't really make sense for us to have a copy of that in each cosmology object, or for us to need cosmology objects to create cosmology-agnostic splines.

**Comment by tilmantroester** [comment]
I agree that the cosmology object is not a great place for spline parameters but making them global is even worse I'd argue. Right now you can have a cosmology object that is tuned for fast execution and one that is tuned for accuracy in the same program. Using global parameters would break this.

**Comment by nikfilippas** [comment]
We can make every function that takes `cosmo` accept an extra argument `spline_params`, which is a dictionary of parameters. Just like how we currently do with the halo profiles and the FFTLog precision parameters. Users can independently tune the calculation to whatever parameters they like, but if they don't do that, then the global spline parameters will be imported and used.

I can see no fundamental reason as to why precision would have to be linked to a particular cosmology, so in essence, you could use the same `Cosmology` object with different spline parameters (which will be passed directly into whatever we want to calculate) with the above proposal.

How does that sound?

**Comment by tilmantroester** [comment]
I agree with all these things. The problem is the C layer, where there are no keyword arguments, no optional arguments, no classes, no methods. Just pain.
Splitting the spline and gsl accuracy parameters (and error status handling) from the cosmology struct would require adding 3 extra arguments to basically every C-level function and making sure the arguments match for every single call. At that point we might as well switch the whole thing to C++, with proper OOP and smart pointers.
