### ISSUE TITLE
Distance calculator

### ISSUE THREAD

**Issue by vittoriodx7** [LSSTDESC/CCL#910]
When computing a particular distance, by default pyccl calls compute_distances() method of Cosmology class, which computes not only the distance required, but also a bunch of other stuff that is not needed by the user. 
Would it be possible to compute these cosmological distances independently from each other? 

In my specific case, I am computing the comoving_angular_distance, and I noticed that changing cosmology and computing it again is quite slow (it takes about 0.1 s per computation on my laptop). Hence I decided to submit this particular issue

for reference, the compute_distances() function is called in all these pyccl functions:
comoving_radial_distance
comoving_angular_distance
angular_diameter_distance
h_over_h0
luminosity_distance
distance_modulus
scale_factor_of_chi

**Comment by c-d-leonard** [comment]
Thanks for submitting this @vittoriodx7 and sorry for the delay without anyone replying.

I believe that at a C level the compute_distances() function computes a(chi), chi(a), and E(a) (where chi is comoving distance and E is H/H0). I haven't profiled it but I expect that either the chi(a) integral or the a(chi) calculation is the rate-limiting step here (rather than E, this should be much quicker that the chi(a) integral). I can see how it would slightly slow down the computation of e.g. comoving_angular_distance to compute a(chi) which is not needed by the comoving_angular_distance function. 

We could consider the idea of whether we should split a(chi) into a different function as I think it is generally not needed for most of these distances. I'm not 100% sure why it was put in that function in the first place and if there are any issues around moving it. @damonge @elisachisari do either of you recall or have any thoughts on this?

How important this is to fix obviously also depends on how big of an issue this extra time is. It sounds like it's becoming an issue for your application?
