### ISSUE TITLE
Fix free Einasto alpha dimension

### ISSUE THREAD

**Issue by hsinfan1996** [LSSTDESC/CCL#988]
The type of Einasto alpha should be a 1D array.

**Comment by hsinfan1996** [comment]
@damonge How can I make self.alpha = None again using `update_parameters`?

**Comment by damonge** [comment]
Oh, right. Hummm, how about we change the default value of alpha in the constructor to `'none'` instead of `None` (and you make it so `None` when calling the constructor also results in `'none'`, to avoid breaking the API). Then, in `update_parameters` if you want to go back to computing alpha from cosmology, you pass `alpha='none'`

**Comment by damonge** [comment]
Or even better than `'none'`, maybe something like `'cosmo'`
